Repository farcasterxyz/contracts, pull requests merged in 2023-02, with the labels that each got.

#167 test: Add some timestamp fuzzing to test coverage
  test/BundleRegistry.t.sol
  test/IdRegistry.t.sol
  test/NameRegistry.t.sol
  test/TestConstants.sol
Labels: chore

#171 docs(fname): regex to match protocol
  docs/docs.md
Labels: docs

#177 refactor: style improvements from the foundry best practices guide
  .vscode/settings.json
  src/IdRegistry.sol
  test/BundleRegistry.t.sol
  test/BundleRegistryGasUsage.t.sol
  test/IdRegistry.t.sol
  test/IdRegistryGasUsage.sol
  test/MetaTx.t.sol
  test/NameRegistry.t.sol
  test/NameRegistryUpgrade.t.sol
  test/Utils.sol
Labels: chore

#178 perf(NameRegistry): followup perf improvements and refactors
  .gas-snapshot
  .vscode/settings.json
  src/NameRegistry.sol
  test/BundleRegistry.t.sol
  test/BundleRegistryGasUsage.t.sol
  test/NameRegistry.t.sol
  test/NameRegistryGasUsage.t.sol
  test/Utils.sol
Labels: docs, perf

#179 perf(IdRegistry): store recovery timestamp and destination in a struct to save gas
  .gas-snapshot
  src/IdRegistry.sol
  test/IdRegistry.t.sol
  test/Utils.sol
Labels: perf

#180 refactor(NameRegistry): rename struct properties in RecoveryState
  src/NameRegistry.sol
  test/NameRegistryUpgrade.t.sol
  test/Utils.sol
Labels: chore
