Repository farcasterxyz/contracts, pull requests merged in 2023-03, with the labels that each got.

#183 feat(NameRegistry): remove inivitation event
  .gas-snapshot
  .vscode/settings.json
  docs/docs.md
  src/BundleRegistry.sol
  src/IdRegistry.sol
  src/NameRegistry.sol
  test/BundleRegistry.t.sol
  test/BundleRegistryGasUsage.t.sol
  test/IdRegistry.t.sol
  test/NameRegistry.t.sol
  test/NameRegistryGasUsage.t.sol
Labels: feat

#184 refactor: use helpers for batch assertions to reduce duplication
  test/NameRegistry.t.sol
Labels: chore

#185 feat(IdRegistry): remove home url
  .gas-snapshot
  src/BundleRegistry.sol
  src/IdRegistry.sol
  test/BundleRegistry.t.sol
  test/BundleRegistryGasUsage.t.sol
  test/IdRegistry.t.sol
  test/IdRegistryGasUsage.sol
  test/MetaTx.t.sol
Labels: feat

#189 chore: fix slither warnings for zero-addr checks, uninitalized values
  .gas-snapshot
  src/BundleRegistry.sol
  src/IdRegistry.sol
  src/NameRegistry.sol
  test/BundleRegistry.t.sol
  test/IdRegistry.t.sol
  test/NameRegistry.t.sol
Labels: chore

#196 ci: call forge-fmt directly instead of using yarn
  .github/workflows/ci.yml
  package.json
Labels: test

#198 ci: parallelize coverage and testing to speed up ci runs
  .github/workflows/ci.yml
Labels: test

#200 refacto: clean up and separate tests into files
  .gas-snapshot
  src/IdRegistry.sol
  test/BundleRegistry.gas.t.sol
  test/BundleRegistry.t.sol
  test/IdRegistry.gas.t.sol
  test/IdRegistry.owner.t.sol
  test/IdRegistry.t.sol
  test/MetaTx.t.sol
  test/NameRegistry.admin.t.sol
  test/NameRegistry.gas.t.sol
  test/NameRegistry.t.sol
  test/NameRegistry.upgrade.t.sol
  test/NameRegistryConstants.sol
  test/TestConstants.sol
Labels: chore

#202 refactor: cleanup comments, imports and variable names
  .gas-snapshot
  src/IdRegistry.sol
  src/NameRegistry.sol
  test/BundleRegistry.t.sol
  test/Utils.sol
Labels: docs, chore

#203 ci: use simple actions instead of codecov
  .github/workflows/ci.yml
Labels: test

#205 perf(NameRegistry): reduce gas usage in reclaim with unchecked math
  src/NameRegistry.sol
  test/NameRegistry.t.sol
Labels: perf

#206 test: fix fuzzer failures where one address collidied with exisiting contracts
  test/NameRegistry.t.sol
Labels: test

#208 test(NameRegistry): unicode string inputs for fnames
  test/NameRegistry.t.sol
Labels: test

#211 test(NameRegistry): add gas tests to cover recovery flow
  .gas-snapshot
  test/NameRegistry.gas.t.sol
Labels: test

#195 test: additional approver transfer tests
  test/NameRegistry.t.sol
Labels: test

#213 refactor: extract TestSuite base contracts
  .gas-snapshot
  test/BundleRegistry/BundleRegistry.gas.t.sol
  test/BundleRegistry/BundleRegistry.t.sol
  test/BundleRegistry/BundleRegistryTestSuite.sol
  test/IdRegistry/IdRegistry.gas.t.sol
  test/IdRegistry/IdRegistry.owner.t.sol
  test/IdRegistry/IdRegistry.t.sol
  test/IdRegistry/IdRegistryTestSuite.sol
  test/MetaTx.t.sol
  test/NameRegistry/NameRegistry.admin.t.sol
  test/NameRegistry/NameRegistry.gas.t.sol
  test/NameRegistry/NameRegistry.t.sol
  test/NameRegistry/NameRegistry.upgrade.t.sol
  test/NameRegistry/NameRegistryConstants.sol
  test/NameRegistry/NameRegistryTestSuite.sol
Labels: chore
