Repository farcasterxyz/contracts, pull requests merged in 2023-07, with the labels that each got.

#233 feat: add Bundler contract
  .gas-snapshot
  src/Bundler.sol
  src/IdRegistry.sol
  test/Bundler/Bundler.t.sol
  test/Bundler/BundlerTestSuite.sol
  test/IdRegistry/IdRegistryTestSuite.sol
  test/StorageRent/StorageRent.t.sol
  test/StorageRent/StorageRentTestSuite.sol
  test/Utils.sol
Labels: feat

#234 feat: add Anvil deploy script
  .env.example
  script/Deploy.s.sol
  script/IdRegistry.s.sol
  script/helpers/IdRegistryFab.sol
Labels: chore

#232 feat: add FnameResolver
  script/helpers/IdRegistryFab.sol
  src/FnameResolver.sol
  test/FnameResolver/FnameResolver.t.sol
  test/FnameResolver/FnameResolverTestSuite.sol
  test/Utils.sol
Labels: feat

#246 fix: cleanup slither warnings
  slither.config.json
  src/Bundler.sol
  src/FnameResolver.sol
  src/StorageRent.sol
  test/StorageRent/StorageRent.t.sol
Labels: bug

#247 chore: use forge fmt --check to fail hook correctly
  .rusty-hook.toml
Labels: chore

#248 refactor(Bundler): clean up documentation, parameter names and types
  .gas-snapshot
  src/Bundler.sol
  src/IdRegistry.sol
  test/Bundler/Bundler.t.sol
  test/IdRegistry/IdRegistry.gas.t.sol
  test/IdRegistry/IdRegistry.owner.t.sol
  test/IdRegistry/IdRegistry.t.sol
Labels: feat

#240 fix: register and exclude known contract addresses
  test/StorageRent/StorageRent.t.sol
  test/StorageRent/StorageRentTestSuite.sol
  test/TestSuiteSetup.sol
Labels: bug

#252 chore: review, disable, and document Slither detectors.
  src/Bundler.sol
  src/StorageRent.sol
  src/lib/TransferHelper.sol
  test/StorageRent/StorageRent.t.sol
Labels: chore

#253 test(Bundler): add case for invalid batches
  test/Bundler/Bundler.t.sol
Labels: test

#250 test: add gas tests
  .gas-snapshot
  test/Bundler/Bundler.gas.t.sol
  test/StorageRent/StorageRent.gas.t.sol
Labels: perf

#251 feat(StorageRent): add emergency price feed override.
  .gas-snapshot
  src/StorageRent.sol
  test/StorageRent/StorageRent.t.sol
  test/Utils.sol
Labels: feat

#261 feat(IdRegistry): require sigs when registering, transferring or recovering to another address
  .env.example
  .gas-snapshot
  script/Deploy.s.sol
  script/IdRegistry.s.sol
  script/helpers/IdRegistryFab.sol
  src/Bundler.sol
  src/IdRegistry.sol
  test/Bundler/Bundler.gas.t.sol
  test/Bundler/Bundler.t.sol
  test/IdRegistry/IdRegistry.gas.t.sol
  test/IdRegistry/IdRegistry.metatx.t.sol
  test/IdRegistry/IdRegistry.owner.t.sol
  test/IdRegistry/IdRegistry.t.sol
  test/IdRegistry/IdRegistryTestSuite.sol
  test/TestConstants.sol
  test/TestSuiteSetup.sol
  test/Utils.sol
Labels: feat

#257 feat: add KeyRegistry
  .vscode/settings.json
  script/Deploy.s.sol
  script/IdRegistry.s.sol
  script/helpers/IdRegistryFab.sol
  src/Bundler.sol
  src/FnameResolver.sol
  src/IdRegistry.sol
  src/KeyRegistry.sol
  test/Bundler/BundlerTestSuite.sol
  test/FnameResolver/FnameResolver.t.sol
  test/FnameResolver/FnameResolverTestSuite.sol
  test/IdRegistry/IdRegistryTestSuite.sol
  test/KeyRegistry/KeyRegistry.t.sol
  test/KeyRegistry/KeyRegistryTestSuite.sol
  test/Utils.sol
Labels: feat

#266 docs(KeyRegistry): add overview docs
  README.md
  docs/docs.md
Labels: docs

#270 docs: explain how contract events are interpreted by hubs
  README.md
  src/IdRegistry.sol
  src/KeyRegistry.sol
  src/StorageRent.sol
Labels: docs

#278 fix: use explicit owner address everywhere
  .gas-snapshot
  src/IdRegistry.sol
  test/Bundler/Bundler.gas.t.sol
  test/Bundler/Bundler.t.sol
  test/FnameResolver/FnameResolver.t.sol
  test/FnameResolver/FnameResolverTestSuite.sol
  test/IdRegistry/IdRegistry.gas.t.sol
  test/IdRegistry/IdRegistry.owner.t.sol
  test/IdRegistry/IdRegistry.t.sol
  test/IdRegistry/IdRegistryTestSuite.sol
  test/KeyRegistry/KeyRegistry.t.sol
  test/KeyRegistry/KeyRegistryTestSuite.sol
  test/TestSuiteSetup.sol
Labels: bug

#260 chore(FnameResolver): add deploy script
  .env.example
  script/FnameResolver.s.sol
Labels: chore

#283 fix: update FnameResolver deploy script
  .env.example
  script/FnameResolver.s.sol
Labels: bug

#281 fix(StorageRent): remove noop revokeRole
  src/StorageRent.sol
Labels: chore

#277 fix(StorageRent): add price feed max age
  .gas-snapshot
  src/StorageRent.sol
  test/StorageRent/StorageRent.t.sol
  test/StorageRent/StorageRentTestSuite.sol
  test/Utils.sol
Labels: bug

#288 chore: add key registry to deploy script
  .env.example
  script/Deploy.s.sol
  script/KeyRegistry.s.sol
Labels: chore

#287 chore: coverage fixups
  test/FnameResolver/FnameResolver.t.sol
  test/StorageRent/StorageRent.t.sol
Labels: chore

#285 feat(Bundler): add key registration to Bundler
  .gas-snapshot
  src/Bundler.sol
  src/IdRegistry.sol
  src/KeyRegistry.sol
  src/lib/Signatures.sol
  src/lib/TrustedCaller.sol
  test/Bundler/Bundler.gas.t.sol
  test/Bundler/Bundler.t.sol
  test/Bundler/BundlerTestSuite.sol
  test/IdRegistry/IdRegistry.owner.t.sol
  test/IdRegistry/IdRegistry.t.sol
  test/IdRegistry/IdRegistryTestSuite.sol
  test/KeyRegistry/KeyRegistry.t.sol
  test/KeyRegistry/KeyRegistryTestSuite.sol
  test/TestSuiteSetup.sol
  test/Utils.sol
Labels: feat

#286 feat(Signatures): support ERC1271 signatures
  .gas-snapshot
  src/lib/Signatures.sol
  test/IdRegistry/IdRegistry.t.sol
  test/KeyRegistry/KeyRegistry.t.sol
Labels: feat

#290 feat(KeyRegistry): add settable IdRegistry
  .gas-snapshot
  src/KeyRegistry.sol
  test/KeyRegistry/KeyRegistry.t.sol
Labels: feat

#289 chore: use ImmutableCreate2Deployer
  .env.example
  .github/workflows/ci.yml
  foundry.toml
  script/Deploy.s.sol
  script/FnameResolver.s.sol
  script/IdRegistry.s.sol
  script/KeyRegistry.s.sol
  script/LocalDeploy.s.sol
  script/StorageRent.s.sol
  script/lib/ImmutableCreate2Deployer.sol
  test/Deploy/Deploy.t.sol
Labels: chore

#291 chore: run spellcheck over code and comments
  src/Bundler.sol
  src/FnameResolver.sol
  src/IdRegistry.sol
  src/KeyRegistry.sol
  src/StorageRent.sol
  src/lib/TrustedCaller.sol
Labels: chore

#298 feat(StorageRent): remove TOTAL_STORAGE_UNIT_CAPACITY
  .gas-snapshot
  docs/docs.md
  src/StorageRent.sol
  test/StorageRent/StorageRent.t.sol
Labels: feat

#299 refactor(StorageRegistry): rename StorageRent to StorageRegistry
  .gas-snapshot
  README.md
  docs/docs.md
  script/Deploy.s.sol
  script/LocalDeploy.s.sol
  script/StorageRegistry.s.sol
  src/Bundler.sol
  src/StorageRegistry.sol
  test/Bundler/Bundler.gas.t.sol
  test/Bundler/Bundler.t.sol
  test/Bundler/BundlerTestSuite.sol
  test/Deploy/Deploy.t.sol
  test/StorageRegistry/StorageRegistry.gas.t.sol
  test/StorageRegistry/StorageRegistry.t.sol
  test/StorageRegistry/StorageRegistryTestSuite.sol
  test/Utils.sol
Labels: chore

#300 refactor(StorageRegistry): rename ADMIN role to OWNER
  .gas-snapshot
  docs/docs.md
  src/StorageRegistry.sol
  test/StorageRegistry/StorageRegistry.t.sol
  test/StorageRegistry/StorageRegistryTestSuite.sol
  test/Utils.sol
Labels: chore
