Repository farcasterxyz/contracts, pull requests merged in 2023-08, with the labels that each got.

#301 feat(IdRegistry): fail transfer, recovery, changeRecovery when paused
  .gas-snapshot
  src/IdRegistry.sol
  test/IdRegistry/IdRegistry.t.sol
Labels: feat

#302 docs: update event invariant docs
  docs/docs.md
  src/IdRegistry.sol
  src/KeyRegistry.sol
  src/StorageRegistry.sol
Labels: docs

#307 chore: update docs, s/pauseRegistrations/pause
  .gas-snapshot
  docs/docs.md
  src/IdRegistry.sol
  test/IdRegistry/IdRegistry.owner.t.sol
  test/IdRegistry/IdRegistry.t.sol
  test/IdRegistry/IdRegistryTestSuite.sol
Labels: chore

#308 feat(StorageRegistry): price bounds, testing and documentation improvements
  .gas-snapshot
  src/StorageRegistry.sol
  test/StorageRegistry/StorageRegistry.t.sol
  test/StorageRegistry/StorageRegistryTestSuite.sol
Labels: feat

#311 feat(StorageRegistry): treasurer should not be able to set price
  docs/docs.md
  src/StorageRegistry.sol
  test/StorageRegistry/StorageRegistry.t.sol
Labels: feat

#310 chore: IdRegistry + KeyRegistry review
  .gas-snapshot
  src/Bundler.sol
  src/FnameResolver.sol
  src/IdRegistry.sol
  src/KeyRegistry.sol
  src/StorageRegistry.sol
  src/lib/TrustedCaller.sol
  test/IdRegistry/IdRegistry.owner.t.sol
  test/IdRegistry/IdRegistry.t.sol
Labels: chore

#313 fix(StorageRegistry): continuousCredit end param should be inclusive
  .gas-snapshot
  src/StorageRegistry.sol
  test/StorageRegistry/StorageRegistry.t.sol
Labels: bug

#317 chore: add signing commits to PR guidelines
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#316 feat(IdRegistry): add view to verify signatures from an fid
  .gas-snapshot
  src/IdRegistry.sol
  test/IdRegistry/IdRegistry.t.sol
  test/IdRegistry/IdRegistryTestSuite.sol
Labels: feat

#315 docs(FnameResolver): add comments
  src/FnameResolver.sol
  test/FnameResolver/FnameResolver.t.sol
Labels: docs

#314 test(StorageRegistry): add docs and tests to improve state coverage
  src/StorageRegistry.sol
  test/StorageRegistry/StorageRegistry.t.sol
Labels: test

#318 chore: use fcast.id domain
  test/FnameResolver/FnameResolverTestSuite.sol
Labels: chore

#319 chore: remove rental period constructor arg
  script/Deploy.s.sol
  script/LocalDeploy.s.sol
  src/StorageRegistry.sol
  test/Deploy/Deploy.t.sol
  test/StorageRegistry/StorageRegistryTestSuite.sol
  test/Utils.sol
Labels: chore

#321 chore: Add Docker Compose file for local development
  docker-compose.yml
Labels: chore

#322 fix: Switch deployer Docker Compose service to use nightly image
  docker-compose.yml
Labels: bug

#323 chore: add network to Docker Compose file
  docker-compose.yml
Labels: chore

#325 chore: Use custom Docker image for local development
  Dockerfile.foundry
  docker-compose.yml
Labels: chore

#326 chore: Improve local dev experience on restart of Anvil container
  Dockerfile.foundry
  docker-compose.yml
Labels: chore

#327 fix: Install specific nightly release
  Dockerfile.foundry
Labels: bug

#324 chore: add skippable setup to deploy script
  .env.example
  docker-compose.yml
  script/Deploy.s.sol
  script/lib/ImmutableCreate2Deployer.sol
Labels: chore

#338 bug(IdRegistry): fix transfer typehash
  src/FnameResolver.sol
  src/IdRegistry.sol
  src/KeyRegistry.sol
  test/FnameResolver/FnameResolver.t.sol
  test/IdRegistry/IdRegistry.t.sol
  test/KeyRegistry/KeyRegistry.t.sol
Labels: bug

#341 fix(StorageRegistry): check that fixed price is in bounds
  src/StorageRegistry.sol
  test/StorageRegistry/StorageRegistry.t.sol
Labels: bug

#350 chore: add tests for InvalidFixedPrice
  test/StorageRegistry/StorageRegistry.t.sol
Labels: chore

#342 fix(KeyRegistry): set fixed gracePeriod
  script/LocalDeploy.s.sol
  src/KeyRegistry.sol
  test/KeyRegistry/KeyRegistryTestSuite.sol
  test/Utils.sol
Labels: bug

#343 feat(Bundler): revert on register with zero storage units
  .gas-snapshot
  src/Bundler.sol
  test/Bundler/Bundler.t.sol
Labels: feat

#344 chore(KeyRegistry): extract fid helper
  .gas-snapshot
  src/KeyRegistry.sol
  test/KeyRegistry/KeyRegistry.t.sol
Labels: chore

#345 chore: remove unused imports
  src/KeyRegistry.sol
  src/lib/TrustedCaller.sol
Labels: chore

#348 chore: natspec cleanup
  src/Bundler.sol
  src/IdRegistry.sol
  src/KeyRegistry.sol
Labels: chore

#349 feat(StorageRegistry): settable data feeds
  .gas-snapshot
  src/StorageRegistry.sol
  test/StorageRegistry/StorageRegistry.t.sol
Labels: feat

#346 feat(IdRegistry): add separate Recover event
  .gas-snapshot
  src/IdRegistry.sol
  test/IdRegistry/IdRegistry.t.sol
Labels: feat

#347 feat(StorageRegistry): add explicit pausability
  .gas-snapshot
  docs/docs.md
  foundry.toml
  src/StorageRegistry.sol
  test/StorageRegistry/StorageRegistry.t.sol
Labels: feat

#351 chore(IdRegistry): expose idCounter and recoveryOf
  .gas-snapshot
  src/IdRegistry.sol
  test/Bundler/Bundler.t.sol
  test/Bundler/BundlerTestSuite.sol
  test/IdRegistry/IdRegistry.t.sol
  test/Utils.sol
Labels: chore

#353 fix: update deploy scripts
  foundry.toml
  script/Deploy.s.sol
Labels: bug

#352 fix: Don't pin version for foundryup
  Dockerfile.foundry
Labels: bug

#356 chore: Add support for toggling blank slate vs forked chain
  .env.example
  docker-compose.yml
Labels: chore

#358 chore: add forge install to docker startup
  docker-compose.yml
Labels: chore

#359 [chore] add missing deployer env vars to docker-compose.yml
  docker-compose.yml
Labels: chore

#354 feat(KeyRegistry): validate key metadata
  .gas-snapshot
  script/Deploy.s.sol
  script/lib/ImmutableCreate2Deployer.sol
  src/Bundler.sol
  src/KeyRegistry.sol
  src/interfaces/IMetadataValidator.sol
  src/interfaces/IdRegistryLike.sol
  src/validators/SignedKeyRequestValidator.sol
  test/Bundler/Bundler.gas.t.sol
  test/Bundler/Bundler.t.sol
  test/Deploy/Deploy.t.sol
  test/KeyRegistry/KeyRegistry.integration.t.sol
  test/KeyRegistry/KeyRegistry.t.sol
  test/KeyRegistry/KeyRegistryTestSuite.sol
  test/Utils.sol
  test/validators/SignedKeyRequestValidator/SignedKeyRequestValidator.t.sol
  test/validators/SignedKeyRequestValidator/SignedKeyRequestValidatorTestSuite.sol
Labels: feat

#355 feat(IdRegistry): add transferFor/changeRecoveryAddressFor
  .gas-snapshot
  src/IdRegistry.sol
  test/IdRegistry/IdRegistry.t.sol
  test/IdRegistry/IdRegistryTestSuite.sol
  test/Utils.sol
Labels: feat

#360 fix: Revert "chore: Add support for toggling blank slate vs forked chain (#356)"
  .env.example
  docker-compose.yml
Labels: bug

#361 chore: key validator followups
  src/validators/SignedKeyRequestValidator.sol
  test/Bundler/Bundler.gas.t.sol
  test/Bundler/BundlerTestSuite.sol
  test/Deploy/Deploy.t.sol
  test/KeyRegistry/KeyRegistry.integration.t.sol
  test/KeyRegistry/KeyRegistry.t.sol
  test/KeyRegistry/KeyRegistryTestSuite.sol
  test/validators/SignedKeyRequestValidator/SignedKeyRequestValidator.t.sol
  test/validators/SignedKeyRequestValidator/SignedKeyRequestValidatorTestSuite.sol
Labels: chore

#362 feat(Bundler): use structs, optional signers
  .gas-snapshot
  src/Bundler.sol
  test/Bundler/Bundler.gas.t.sol
  test/Bundler/Bundler.t.sol
  test/Deploy/Deploy.t.sol
Labels: feat

#364 chore: update SignedKeyRequestValidator name
  src/validators/SignedKeyRequestValidator.sol
Labels: chore

#365 fix: add metadata to KeyRegistry batches
  .gas-snapshot
  src/KeyRegistry.sol
  src/validators/SignedKeyRequestValidator.sol
  test/Deploy/Deploy.t.sol
  test/KeyRegistry/KeyRegistry.integration.t.sol
  test/KeyRegistry/KeyRegistry.t.sol
  test/KeyRegistry/KeyRegistryTestHelpers.sol
  test/validators/SignedKeyRequestValidator/SignedKeyRequestValidator.t.sol
Labels: bug

#366 chore: document structs, helper cleanup
  src/KeyRegistry.sol
  test/KeyRegistry/KeyRegistry.t.sol
  test/KeyRegistry/KeyRegistryTestHelpers.sol
Labels: chore

#367 chore: update deployment parameters
  .env.example
  foundry.toml
  script/Deploy.s.sol
  script/lib/ImmutableCreate2Deployer.sol
  test/Deploy/Deploy.t.sol
Labels: chore

#369 chore: L1 deploy script
  .env.example
  .github/workflows/ci.yml
  docker-compose.yml
  foundry.toml
  script/DeployL1.s.sol
  script/DeployL2.s.sol
  src/FnameResolver.sol
  test/Deploy/DeployL1.t.sol
  test/Deploy/DeployL2.t.sol
  test/FnameResolver/FnameResolverTestSuite.sol
  test/Utils.sol
Labels: chore

#370 chore: extract shared EIP712 base contract
  .gas-snapshot
  src/FnameResolver.sol
  src/IdRegistry.sol
  src/KeyRegistry.sol
  src/lib/EIP712.sol
  src/validators/SignedKeyRequestValidator.sol
  test/Bundler/BundlerTestSuite.sol
  test/Deploy/DeployL1.t.sol
  test/FnameResolver/FnameResolver.t.sol
  test/FnameResolver/FnameResolverTestSuite.sol
  test/IdRegistry/IdRegistry.gas.t.sol
  test/IdRegistry/IdRegistry.owner.t.sol
  test/IdRegistry/IdRegistry.t.sol
  test/IdRegistry/IdRegistryTestSuite.sol
  test/KeyRegistry/KeyRegistry.integration.t.sol
  test/KeyRegistry/KeyRegistry.t.sol
  test/KeyRegistry/KeyRegistryTestSuite.sol
  test/Utils.sol
  test/validators/SignedKeyRequestValidator/SignedKeyRequestValidator.t.sol
  test/validators/SignedKeyRequestValidator/SignedKeyRequestValidatorTestSuite.sol
Labels: chore

#371 chore: update versions
  .gas-snapshot
  src/Bundler.sol
  src/FnameResolver.sol
  src/IdRegistry.sol
  src/KeyRegistry.sol
  src/StorageRegistry.sol
  src/validators/SignedKeyRequestValidator.sol
  test/Bundler/Bundler.t.sol
  test/FnameResolver/FnameResolver.t.sol
  test/IdRegistry/IdRegistry.t.sol
  test/KeyRegistry/KeyRegistry.t.sol
  test/StorageRegistry/StorageRegistry.t.sol
  test/validators/SignedKeyRequestValidator/SignedKeyRequestValidator.t.sol
Labels: chore

#373 chore: add L1 services to docker-compose
  docker-compose.yml
Labels: chore

#375 chore: natspec fixes
  src/Bundler.sol
  src/IdRegistry.sol
  src/KeyRegistry.sol
Labels: chore

#376 feat: add name to id registry
  .gas-snapshot
  src/IdRegistry.sol
  test/IdRegistry/IdRegistry.t.sol
Labels: feat

#379 fix: Install specific version to prevent builds breaking
  Dockerfile.foundry
Labels: bug

#378 feat: add RecoveryProxy
  .env.example
  docker-compose.yml
  script/DeployL2.s.sol
  src/RecoveryProxy.sol
  test/Deploy/DeployL2.t.sol
  test/RecoveryProxy/RecoveryProxy.t.sol
  test/RecoveryProxy/RecoveryProxyTestSuite.sol
Labels: feat

#380 fix: Ensure env var references can be passed via `include` direction of Docker Compose
  docker-compose.yml
Labels: bug

#377 refactor: add interfaces
  script/DeployL2.s.sol
  src/Bundler.sol
  src/IdRegistry.sol
  src/KeyRegistry.sol
  src/StorageRegistry.sol
  src/interfaces/IBundler.sol
  src/interfaces/IIdRegistry.sol
  src/interfaces/IKeyRegistry.sol
  src/interfaces/IStorageRegistry.sol
  test/Bundler/Bundler.gas.t.sol
  test/Bundler/Bundler.t.sol
  test/Deploy/DeployL2.t.sol
  test/KeyRegistry/KeyRegistry.integration.t.sol
  test/KeyRegistry/KeyRegistry.t.sol
Labels: feat

#381 fix: fix fuzz assume
  foundry.toml
  test/KeyRegistry/KeyRegistry.integration.t.sol
Labels: bug

#383 chore: update contract heading natspec
  src/Bundler.sol
  src/FnameResolver.sol
  src/IdRegistry.sol
  src/KeyRegistry.sol
  src/RecoveryProxy.sol
  src/StorageRegistry.sol
  src/validators/SignedKeyRequestValidator.sol
Labels: chore

#384 chore: use inheritdoc tag
  src/IdRegistry.sol
  src/KeyRegistry.sol
  src/StorageRegistry.sol
  src/interfaces/IIdRegistry.sol
  src/interfaces/IKeyRegistry.sol
  test/RecoveryProxy/RecoveryProxy.t.sol
Labels: chore

#386 chore: add license IDs
  src/Bundler.sol
  src/interfaces/IBundler.sol
  src/interfaces/IKeyRegistry.sol
  src/interfaces/IMetadataValidator.sol
  src/interfaces/IStorageRegistry.sol
  src/lib/EIP712.sol
  src/lib/Signatures.sol
  src/lib/TransferHelper.sol
  src/validators/SignedKeyRequestValidator.sol
Labels: chore

#388 chore: update recovery proxy salt
  script/DeployL2.s.sol
Labels: chore

#389 chore: add v3 deployment
  README.md
  test/Deploy/DeployL2.t.sol
Labels: chore
